PreCommit:
  RuboCop:
    enabled: false
    on_warn: fail
    problem_on_unmodified_line: ignore
    flags: ['--disable-pending-cops']
  RailsBestPractices:
    enabled: false
    on_warn: fail
    problem_on_unmodified_line: ignore
PrePush:
  Brakeman:
    enabled: false
    on_warn: fail
    problem_on_unmodified_line: ignore
