PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
  RailsBestPractices:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore
PrePush:
  Brakeman:
    enabled: true
    on_warn: fail
    problem_on_unmodified_line: ignore