Metrics/ClassLength:
  Description: 'Avoid classes longer than 100 lines of code.'
  Max: 100
  Enabled: true
Metrics/ModuleLength:
  Description: 'Avoid modules longer than 100 lines of code.'
  Max: 100
  Enabled: true
Metrics/ParameterLists:
  Description: 'Pass no more than four parameters into a method.'
  Max: 4
  Enabled: true
Metrics/MethodLength:
  Description: 'Avoid methods longer than 20 lines of code.'
  Max: 20
  Enabled: true
Metrics/BlockLength:
  CountComments: false
  Max: 20
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*


