
development:
  adapter: postgresql
  encoding: unicode
  database: INNOVATION_FORPOST
  pool: 5
  username: stas
  password:
  timeout: 5000
 
 
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: unicode
  database: INNOVATION_FORPOST_test
  pool: 5
  username: stas
  password:
  timeout: 5000